Play:
  No-Coins-Take-Money: 500
  Buy-Coins-Take-Money: 500
  Respawn-Count-Time: 5
  New-Player-Coins: 9
  Before-Respawn-Game-Mode: "SPECTATOR"
  After-Respawn-Game-Mode: "SURVIVAL"
Mysql:
  Host: "localhost"
  Port: 3306
  Database: "test"
  Username: "tester"
  Password: "tester"
  UseSSL: false
Warp:
  World: "world"
  X: 0.0
  Y: 0.0
  Z: 0.0
ReviveCoin:
  ==: org.bukkit.inventory.ItemStack
    type: GOLD_NUGGET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §a✔ 复活粒
      lore:
        - " "
        - §7复活粒
        - §7右键可以获得一枚复活币
        - " "
        - §a▶ 点击使用
