

#         Powered by TabooLib 5.32         #


name: ${name}
main: ${main}
main-transfer: ${mainTransfer}
version: ${version}
author: ${author}

api-version: 1.13

depend: [Vault, ParrotX, MicalLib]
softdepend: [PlaceholderAPI]
authors: [Mical]
