name: ReviveCoinReremake
main: cn.galaxy233.revivecoinreremake.ReviveCoinReremake
version: @version@

api-version: 1.13

depend: [Vault, ParrotX, MicalLib]
softdepend: [PlaceholderAPI]
authors: [Mical]

commands:
  revivecoin:
