name: ReviveCoinReremake
main: me.mical.revivecoinreremake.ReviveCoinReremake
version: @version@

api-version: "1.13"

depend: [Vault, ParrotX, MicalLib]
softdepend: [PlaceholderAPI]
authors: [Mical]

commands:
  revivecoin:
